### ISSUE TITLE
test for: is the MO up-to-date? 

### ISSUE THREAD

**Issue by syphar** [Thermondo/pytest-translations#2]
this one is probably django-specific, since the discovery-settings in `makemessages` are.

**Comment by syphar** [comment]
we need either a local `xgettext` installation for this, or use a library like `babel`

**Comment by codingjoe** [comment]
you need `xgettext` anyway to use i18n

**Comment by syphar** [comment]
why?

**Comment by codingjoe** [comment]
well django needs xgettext to run `compilemessages`

**Comment by syphar** [comment]
Do check if the `mo` is up-to-date you don't need `compilemessages`.

It's about message discovery (`makemessages`) and the content of the `mo`

**Comment by codingjoe** [comment]
Chicken or the egg?

**Comment by syphar** [comment]
I don't understand ... ? 

This issue is for catching the case that you marked strings for translation in your code, but didn't run `makemessages`. 

What do you mean?

**Comment by codingjoe** [comment]
Ok, I though you wanted to actually compile the PO into an MO file.

What Is it you want to detect exactly? That the MO file is proper representation of PO or that it changed?

I feel, that this is over the top. We could rather extend our buildpack to compile all PO files.

**Comment by syphar** [comment]
currently we test (already): 
- mo == po
- contents of the po (empty entries, fuzzy entries). 

So the only step not tested is: 
- does the po contain all entries marked for translation.

**Comment by syphar** [comment]
but you'll see it if you finally review the plugin ;)

**Comment by syphar** [comment]
closing for now, is more nice-to have,
